font_family      family='AdwaitaMono Nerd Font Mono'
font_size 11

confirm_os_window_close 0
enable_audio_bell no
cursor_shape block

disable ligatures yes
shell_integration disabled

url_style curly
window_padding_width 25
remember_window_size no

cursor_blink_interval 0
sync_to_monitor no

repaint_delay 8
input_delay 3

background_opacity 0.8
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

cursor_trail 3